version: '3.8'

services:
  dynamo:
    container_name: dynamodb
    image: amazon/dynamodb-local
    networks:
      - local-network
    ports:
      - '8000:8000'
    volumes:
      - dynamodata:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath .'

  mysql:
    container_name: mysql
    image: mysql:8.0
    networks:
      - local-network
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-bp_manager}
      MYSQL_USER: ${MYSQL_USER:-bp_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-bp_password}
    volumes:
      - mysqldata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  local-network:
    name: local-network

volumes:
  dynamodata: {}
  mysqldata: {}
